development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: rolodexx_development
  pool: 5
  username: rolodexx
  password: rolodexx

test:
  adapter: sqlite3
  database: ":memory:"
  verbosity: quiet
